name = "tutorial"
defaultTargets = [ "Tutorial" ]

[[require]]
name = "Lean4Export"
git = "https://github.com/leanprover/lean4export"
rev = "arena_json_output"

[[lean_lib]]
name = "Tutorial"
root = "Tutorial"